# Place this file at the REPO ROOT as: netlify.toml

[build]
  # For a pure static site with index.html at the root:
  publish = "."
  # If you don't have a build step, omit 'command' entirely
  # command = ""

# Global security headers (CSP allows Netlify reCAPTCHA)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    # CSP tuned to allow Google reCAPTCHA
    Content-Security-Policy = """
      default-src 'self';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      connect-src 'self';
      img-src 'self' data: https://www.gstatic.com https://www.google.com;
      style-src 'self' 'unsafe-inline';
      script-src 'self' 'unsafe-inline' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/;
      frame-src 'self' https://www.google.com/ https://www.google.com/recaptcha/;
      font-src 'self' data:;
    """
